artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_loader:
  root_dir: artifacts/raw_datasets
  dataset_name: sp46d/xsum-6k
  local_data_path: artifacts/raw_datasets/xsum_6k

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/raw_datasets/xsum_6k
  base_model: google/pegasus-large
  fine_tuned_model: google/pegasus-xsum
  out_dir: pegasus-xsum
  use_fine_tuned_model: True


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/raw_datasets/xsum_6k
  model_path: artifacts/model_trainer/pegasus-xsum
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv